// Real JCPenney category taxonomy sourced from their Search API facets
export const JCP_CATEGORIES = {
  "Women's Clothing": [
    "t-shirts", "blouses", "tunic tops", "tank tops", "camisoles", "crop top",
    "pullover sweaters", "cardigans", "polo sweaters", "sweatshirts", "hoodies",
    "fit + flare dresses", "a-line dresses", "maxi dresses", "sheath dresses",
    "wrap dresses", "sundresses", "bodycon dresses", "shirt dresses", "swing dresses",
    "party dresses", "evening gowns", "ball gowns", "skater dresses",
    "straight leg jeans", "skinny jeans", "bootcut jeans", "flare jeans",
    "boyfriend jeans", "cropped jeans", "jeggings", "loose fit jeans",
    "pull-on pants", "cargo pants", "palazzo pants", "trousers", "capri pants",
    "jogger pants", "leggings", "full length leggings", "yoga pants",
    "a-line skirts", "maxi skirts", "pencil skirts", "pleated skirts", "mini skirts",
    "blazers", "denim jackets", "bomber jackets", "fleece jackets", "trench coats",
    "full coverage bras", "sports bras", "bralettes", "push up bras", "strapless bras",
    "brief panties", "hipster panties", "thong panties", "boyshort panties",
    "pajama sets", "pajama pants", "robes", "nightgowns", "sleepwear",
    "one piece swimsuits", "bikini", "tankinis", "swim shorts", "swim dresses",
    "short sets", "pant sets", "rompers", "jumpsuits",
  ],
  "Men's Clothing": [
    "dress shirts", "button-down shirts", "polo shirts", "graphic t-shirts",
    "t-shirts", "henley shirts", "flannel shirts", "camp shirts", "western shirts",
    "pullover sweaters", "cardigans", "quarter-zip pullover", "sweatshirts", "hoodies",
    "straight leg jeans", "slim fit jeans", "relaxed fit jeans", "cargo pants",
    "flat front pants", "trousers", "chino shorts", "cargo shorts", "swim shorts",
    "suit jackets", "suit pants", "blazers", "sport coats", "suit sets", "tuxedos",
    "denim jackets", "bomber jackets", "fleece jackets", "softshell jackets",
    "boxer briefs", "boxers", "briefs", "undershirts",
    "pajama sets", "pajama pants", "robes",
    "track suits", "track pants", "workout shorts", "jogger pants",
  ],
  "Kids & Baby": [
    "graphic t-shirts", "t-shirts", "button-down shirts", "polo shirts",
    "hoodies", "sweatshirts", "pajama sets", "kids pajama sets", "one piece pajamas",
    "dresses", "skirts", "leggings", "jeans", "shorts", "pants",
    "school uniforms", "scrub tops", "layette sets", "bibs", "burp cloths",
    "baby gift sets", "footed pajamas", "romper sets", "bodysuit sets",
    "sneakers", "dress up shoes", "baby booties", "toddler shoes",
  ],
  "Shoes": [
    "sneakers", "running shoes", "slip-on shoes", "loafers", "oxford shoes",
    "boat shoes", "work shoes", "mary jane shoes", "ballet flats", "clogs",
    "heeled sandals", "flat sandals", "wedge sandals", "strap sandals",
    "slide sandals", "flip-flops", "footbed sandals",
    "dress boots", "ankle boots", "chelsea boots", "cowboy boots",
    "over the knee boots", "winter boots", "combat boots", "lace up boots",
    "booties", "slouch boots",
    "pumps", "mules",
  ],
  "Home & Bedding": [
    "comforter sets", "sheet sets", "duvet cover sets", "quilt sets",
    "bed pillows", "throw pillows", "pillow shams", "bed skirts",
    "mattress pads", "mattress protectors", "mattress toppers", "featherbeds",
    "blankets", "throws", "coverlets", "bedspreads",
    "curtain panels", "valances", "window tiers", "roman shades",
    "area rugs", "accent rugs", "runners", "rug sets",
    "bath towel sets", "bath towels", "hand towels", "washcloths",
    "shower curtains", "shower curtain sets", "bath accessory sets",
    "kitchen towels", "dish cloths", "placemats", "tablecloths", "table runners",
  ],
  "Furniture": [
    "accent chairs", "recliners", "ottomans", "benches",
    "accent tables", "coffee table sets", "nightstands", "desks",
    "dining chairs", "dining tables", "bar stools", "pub sets",
    "bookcases", "headboards", "beds", "bunk beds",
    "office chairs", "kitchen islands", "kitchen carts", "serving carts",
  ],
  "Jewelry & Accessories": [
    "drop earrings", "hoop earrings", "chandelier earrings",
    "collar necklaces", "bridal sets", "engagement rings",
    "bracelet watches", "strap watches", "bangle watches", "expansion watches",
    "crossbody bags", "evening bags", "backpacks", "wallets", "clutches",
    "belts", "scarves", "gloves", "sunglasses", "baseball caps",
    "bow ties", "ties", "tie sets", "cufflinks",
  ],
  "Sports & Active": [
    "sports bras", "yoga pants", "workout pants", "workout shorts",
    "running shoes", "sneakers", "athletic jackets", "fleece jackets",
    "compression socks", "swim shirts", "rash guards", "swim goggles",
    "track suits", "track pants", "basketball shorts", "soccer shorts",
    "golf shorts", "golf pants", "bike shorts",
  ],
  "Kitchen & Dining": [
    "cookware sets", "skillets", "frying pans", "sauce pans", "stockpots",
    "dutch ovens", "bakeware sets", "knife sets", "dinnerware sets",
    "coffee mugs", "tumblers", "water bottles",
    "air fryers", "slow cookers", "stand mixers", "blenders", "toasters",
    "kitchen utensil sets", "cutting boards", "pot holders",
  ],
};

// Flat list of all JCPenney search terms for the LLM prompt
export const ALL_JCP_TERMS = Object.values(JCP_CATEGORIES).flat();
